// <auto-generated />
using System;
using MODULE4HW6;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MODULE4HW6.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MODULE4HW6.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArtistId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InstagramUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            DateOfBirth = new DateTime(1990, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asd@aa.aa",
                            InstagramUrl = "instagram.com/artur",
                            Name = "Artur",
                            Phone = "05055333"
                        },
                        new
                        {
                            ArtistId = 2,
                            DateOfBirth = new DateTime(1990, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asd@aa.aa11",
                            InstagramUrl = "instagram.com/artur1",
                            Name = "Artur1",
                            Phone = "0339393"
                        },
                        new
                        {
                            ArtistId = 3,
                            DateOfBirth = new DateTime(1990, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asd@aa.aa22",
                            InstagramUrl = "instagram.com/artur2",
                            Name = "Artur2",
                            Phone = "0339393"
                        },
                        new
                        {
                            ArtistId = 4,
                            DateOfBirth = new DateTime(1989, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asd@aa.aa33",
                            InstagramUrl = "instagram.com/artur3",
                            Name = "Artur3",
                            Phone = "023283"
                        },
                        new
                        {
                            ArtistId = 5,
                            DateOfBirth = new DateTime(1989, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asd@aa.aa44",
                            InstagramUrl = "instagram.com/artur4",
                            Name = "Artur14",
                            Phone = "123823"
                        });
                });

            modelBuilder.Entity("MODULE4HW6.Models.ArtistsToSong", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int")
                        .HasColumnName("ArtistId");

                    b.Property<int>("SongId")
                        .HasColumnType("int")
                        .HasColumnName("SongId");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistsToSong");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            SongId = 2
                        },
                        new
                        {
                            ArtistId = 2,
                            SongId = 1
                        },
                        new
                        {
                            ArtistId = 3,
                            SongId = 4
                        },
                        new
                        {
                            ArtistId = 4,
                            SongId = 5
                        },
                        new
                        {
                            ArtistId = 1,
                            SongId = 3
                        });
                });

            modelBuilder.Entity("MODULE4HW6.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GenreId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Title = "Rock"
                        },
                        new
                        {
                            GenreId = 2,
                            Title = "Rap"
                        },
                        new
                        {
                            GenreId = 3,
                            Title = "Trance"
                        },
                        new
                        {
                            GenreId = 4,
                            Title = "Techno"
                        },
                        new
                        {
                            GenreId = 5,
                            Title = "Pop"
                        });
                });

            modelBuilder.Entity("MODULE4HW6.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SongId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Duration");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("SongId");

                    b.HasIndex("GenreId");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            Duration = "4m.56s",
                            GenreId = 1,
                            ReleasedDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song#1"
                        },
                        new
                        {
                            SongId = 2,
                            Duration = "5m.56s",
                            GenreId = 2,
                            ReleasedDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song#2"
                        },
                        new
                        {
                            SongId = 3,
                            Duration = "2m.16s",
                            GenreId = 3,
                            ReleasedDate = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song#3"
                        },
                        new
                        {
                            SongId = 4,
                            Duration = "4m.56s",
                            GenreId = 4,
                            ReleasedDate = new DateTime(2017, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song#4"
                        },
                        new
                        {
                            SongId = 5,
                            Duration = "2m.16s",
                            GenreId = 2,
                            ReleasedDate = new DateTime(2015, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Song#5"
                        });
                });

            modelBuilder.Entity("MODULE4HW6.Models.ArtistsToSong", b =>
                {
                    b.HasOne("MODULE4HW6.Models.Artist", "Artist")
                        .WithMany("ArtistsToSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODULE4HW6.Models.Song", "Song")
                        .WithMany("ArtistsToSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MODULE4HW6.Models.Song", b =>
                {
                    b.HasOne("MODULE4HW6.Models.Genre", "Genre")
                        .WithMany("SongList")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MODULE4HW6.Models.Artist", b =>
                {
                    b.Navigation("ArtistsToSongs");
                });

            modelBuilder.Entity("MODULE4HW6.Models.Genre", b =>
                {
                    b.Navigation("SongList");
                });

            modelBuilder.Entity("MODULE4HW6.Models.Song", b =>
                {
                    b.Navigation("ArtistsToSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
